spring:
    profile:
        active: dev,test,prod
    application:
        name: api
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/vollmed-api
        username: root
        password: ${DB_PASSWORD}
    jpa:
        show-sql: true
        properties:
                hibernate:
                    format_sql: true
server:
    error:
        include-stacktrace: never
        #En este caso es el stacktrace lo que sacamos para evitar que salgan datos sensibles


api:
    security:
        secret: 123456 #La idea es que cree una variable de entorno para esto
